// app/layout.jsx  (server component)
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import BackToTop from "./dashboard/components/shared/BackToTop";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "TicketHub",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap only the client-side providers */}
        <Providers>
          <Navbar />
          {children}
          <Toaster position="top-right" />
          <Footer />
          <BackToTop/>
        </Providers>
      </body>
    </html>
  );
}