// lib/eventsData.js
export const eventsData = {
  movies: [
    {
      id: 1,
      title: "Avengers: Endgame",
      date: "2025-10-12",
      location: "Star Cineplex, Dhaka",
      price: 500,
      desc: "The final showdown of Marvel’s Avengers saga.",
      image: "/events/movies/avengers.jpg",
    },
    {
      id: 2,
      title: "Oppenheimer",
      date: "2025-11-01",
      location: "Blockbuster Cinemas, Dhaka",
      price: 600,
      desc: "The epic biopic of J. Robert Oppenheimer.",
      image: "/events/movies/oppenheimer.jpg",
    },
    {
      id: 3,
      title: "Spider-Man: No Way Home",
      date: "2025-09-25",
      location: "Shyamoli Cinema, Dhaka",
      price: 450,
      desc: "Spider-Man faces villains from the multiverse.",
      image: "/events/movies/spiderman.jpg",
    },
    {
      id: 4,
      title: "Inception",
      date: "2025-12-05",
      location: "Star Cineplex, Chittagong",
      price: 400,
      desc: "A sci-fi thriller about dreams within dreams.",
      image: "/events/movies/inception.jpg",
    },
    {
      id: 5,
      title: "The Batman",
      date: "2025-10-28",
      location: "Rupali Cinema, Sylhet",
      price: 480,
      desc: "Batman uncovers Gotham’s darkest secrets.",
      image: "/events/movies/batman.jpg",
    },
    {
      id: 6,
      title: "Dune: Part Two",
      date: "2025-11-15",
      location: "Silver Screen, Dhaka",
      price: 550,
      desc: "Continuation of the sci-fi masterpiece Dune.",
      image: "/events/movies/dune.jpg",
    },
    {
      id: 7,
      title: "Frozen II",
      date: "2025-12-20",
      location: "Star Cineplex, Dhaka",
      price: 350,
      desc: "Anna and Elsa go on a magical journey.",
      image: "/events/movies/frozen.jpg",
    },
    {
      id: 8,
      title: "Avatar: The Way of Water",
      date: "2025-10-18",
      location: "Blockbuster Cinemas, Dhaka",
      price: 650,
      desc: "Return to Pandora in James Cameron’s epic sequel.",
      image: "/events/movies/avatar.jpg",
    },
  ],
  concerts: [
    {
      id: 1,
      title: "Rock Concert 2025",
      date: "2025-10-22",
      location: "Army Stadium, Dhaka",
      price: 1200,
      desc: "Bangladesh’s biggest rock concert with top bands.",
      image: "/events/concerts/rock.jpg",
    },
    {
      id: 2,
      title: "Classical Evening",
      date: "2025-11-05",
      location: "Bangladesh Shilpakala Academy",
      price: 800,
      desc: "An evening of classical music and symphony.",
      image: "/events/concerts/classical.jpg",
    },
    {
      id: 3,
      title: "EDM Night",
      date: "2025-12-01",
      location: "International Convention Center, Dhaka",
      price: 1500,
      desc: "Electronic dance music with top DJs.",
      image: "/events/concerts/edm.jpg",
    },
    {
      id: 4,
      title: "Folk Festival",
      date: "2025-12-10",
      location: "Suhrawardy Udyan, Dhaka",
      price: 600,
      desc: "Folk songs and performances from across Bangladesh.",
      image: "/events/concerts/folk.jpg",
    },
    {
      id: 5,
      title: "Bollywood Beats",
      date: "2025-11-25",
      location: "BICC, Dhaka",
      price: 1000,
      desc: "A night of Bollywood music and dance.",
      image: "/events/concerts/bollywood.jpg",
    },
    {
      id: 6,
      title: "Jazz Night",
      date: "2025-10-30",
      location: "Dhaka Club",
      price: 900,
      desc: "Smooth jazz performances from international artists.",
      image: "/events/concerts/jazz.jpg",
    },
    {
      id: 7,
      title: "Metal Mania",
      date: "2025-12-15",
      location: "Chittagong Stadium",
      price: 1300,
      desc: "Hard rock and metal concert for metalheads.",
      image: "/events/concerts/metal.jpg",
    },
    {
      id: 8,
      title: "Pop Gala",
      date: "2025-11-12",
      location: "Sylhet Stadium",
      price: 1100,
      desc: "Pop singers performing top chart hits.",
      image: "/events/concerts/pop.jpg",
    },
  ],
  theater: [
    {
      id: 1,
      title: "Hamlet",
      date: "2025-10-05",
      location: "National Theater Hall, Dhaka",
      price: 400,
      desc: "Shakespeare’s iconic tragedy performed by Dhaka Theatre.",
      image: "/events/theater/hamlet.jpg",
    },
    {
      id: 2,
      title: "Macbeth",
      date: "2025-10-20",
      location: "Bangladesh Shilpakala Academy",
      price: 450,
      desc: "A dark tale of ambition and fate.",
      image: "/events/theater/macbeth.jpg",
    },
    {
      id: 3,
      title: "The Tempest",
      date: "2025-11-10",
      location: "Star Theater, Dhaka",
      price: 420,
      desc: "A magical island tale directed by local artists.",
      image: "/events/theater/tempest.jpg",
    },
    {
      id: 4,
      title: "A Streetcar Named Desire",
      date: "2025-12-01",
      location: "Dhaka Drama Hall",
      price: 380,
      desc: "Classic American play about human emotions.",
      image: "/events/theater/streetcar.jpg",
    },
    {
      id: 5,
      title: "King Lear",
      date: "2025-12-12",
      location: "Sylhet Theater",
      price: 430,
      desc: "A tragic story of a king and his daughters.",
      image: "/events/theater/kinglear.jpg",
    },
    {
      id: 6,
      title: "Romeo and Juliet",
      date: "2025-10-28",
      location: "Rajshahi Theater",
      price: 400,
      desc: "Timeless love story by Shakespeare.",
      image: "/events/theater/romeo.jpg",
    },
    {
      id: 7,
      title: "Waiting for Godot",
      date: "2025-11-18",
      location: "Experimental Theater Hall, Dhaka",
      price: 390,
      desc: "Absurdist play by Samuel Beckett.",
      image: "/events/theater/godot.jpg",
    },
    {
      id: 8,
      title: "Oedipus Rex",
      date: "2025-12-25",
      location: "Dhaka Theater Hall",
      price: 410,
      desc: "Greek tragedy about fate and destiny.",
      image: "/events/theater/oedipus.jpg",
    },
  ],
  sports: [
    {
      id: 1,
      title: "Bangladesh vs India (Cricket)",
      date: "2025-10-22",
      location: "Sher-e-Bangla Stadium, Dhaka",
      price: 1500,
      desc: "Cricket rivalry match between Bangladesh and India.",
      image: "/events/sports/cricket.jpg",
    },
    {
      id: 2,
      title: "Dhaka Derby (Football)",
      date: "2025-11-10",
      location: "Bangabandhu Stadium, Dhaka",
      price: 1000,
      desc: "The biggest football match in Bangladesh.",
      image: "/events/sports/football.jpg",
    },
    {
      id: 3,
      title: "Sylhet Marathon",
      date: "2025-12-01",
      location: "Sylhet City",
      price: 500,
      desc: "Annual marathon event in Sylhet.",
      image: "/events/sports/marathon.jpg",
    },
    {
      id: 4,
      title: "Basketball Championship",
      date: "2025-12-15",
      location: "Indoor Stadium, Chittagong",
      price: 700,
      desc: "National basketball tournament finals.",
      image: "/events/sports/basketball.jpg",
    },
    {
      id: 5,
      title: "Tennis Open",
      date: "2025-11-28",
      location: "National Tennis Complex, Dhaka",
      price: 600,
      desc: "Bangladesh Open tennis competition.",
      image: "/events/sports/tennis.jpg",
    },
    {
      id: 6,
      title: "Hockey League Finals",
      date: "2025-12-05",
      location: "Maulana Bhashani Stadium, Dhaka",
      price: 650,
      desc: "National hockey league final match.",
      image: "/events/sports/hockey.jpg",
    },
    {
      id: 7,
      title: "Kabaddi Tournament",
      date: "2025-11-20",
      location: "Rajshahi Stadium",
      price: 400,
      desc: "Traditional kabaddi tournament.",
      image: "/events/sports/kabaddi.jpg",
    },
    {
      id: 8,
      title: "Cycling Championship",
      date: "2025-12-22",
      location: "Cox’s Bazar Highway",
      price: 550,
      desc: "Cycling competition along scenic routes.",
      image: "/events/sports/cycling.jpg",
    },
  ],
  travel: [
    {
      id: 1,
      title: "Dhaka to Chittagong Flight",
      date: "2025-10-15",
      location: "Hazrat Shahjalal Airport, Dhaka",
      price: 4500,
      desc: "Quick domestic flight with Air Bangladesh.",
      image: "/events/travel/flight-dhaka-ctg.jpg",
    },
    {
      id: 2,
      title: "Dhaka to Sylhet Train",
      date: "2025-10-18",
      location: "Kamalapur Railway Station, Dhaka",
      price: 800,
      desc: "Enjoy the scenic train journey to Sylhet.",
      image: "/events/travel/train-sylhet.jpg",
    },
    {
      id: 3,
      title: "Cox’s Bazar Express Bus",
      date: "2025-11-02",
      location: "Gabtoli Bus Terminal, Dhaka",
      price: 1200,
      desc: "Luxury AC bus service to Cox’s Bazar.",
      image: "/events/travel/bus-cox.jpg",
    },
    {
      id: 4,
      title: "Dhaka to Kolkata Flight",
      date: "2025-11-12",
      location: "Hazrat Shahjalal Airport, Dhaka",
      price: 7500,
      desc: "International trip from Dhaka to Kolkata.",
      image: "/events/travel/flight-kolkata.jpg",
    },
    {
      id: 5,
      title: "Rangamati Tour Boat",
      date: "2025-11-20",
      location: "Kaptai Lake, Rangamati",
      price: 1500,
      desc: "Boat tour across the beautiful Kaptai Lake.",
      image: "/events/travel/boat-rangamati.jpg",
    },
    {
      id: 6,
      title: "Dhaka to Barisal Launch",
      date: "2025-12-01",
      location: "Sadarghat Launch Terminal, Dhaka",
      price: 1000,
      desc: "Overnight launch trip to Barisal.",
      image: "/events/travel/launch-barisal.jpg",
    },
    {
      id: 7,
      title: "Bandarban Trekking Trip",
      date: "2025-12-10",
      location: "Bandarban Hill Tracts",
      price: 2000,
      desc: "Adventure trekking through Bandarban hills.",
      image: "/events/travel/trek-bandarban.jpg",
    },
    {
      id: 8,
      title: "Saint Martin Cruise",
      date: "2025-12-20",
      location: "Teknaf to Saint Martin Island",
      price: 3500,
      desc: "Sea cruise to Saint Martin’s Island.",
      image: "/events/travel/cruise-saintmartin.jpg",
    },
  ],
  workshops: [
    {
      id: 1,
      title: "Cooking Masterclass",
      date: "2025-10-15",
      location: "Dhaka Culinary School",
      price: 1500,
      desc: "Learn international cuisines from master chefs.",
      image: "/events/workshops/cooking.jpg",
    },
    {
      id: 2,
      title: "Photography Workshop",
      date: "2025-10-22",
      location: "Dhaka Art Institute",
      price: 1200,
      desc: "Basics of photography and editing skills.",
      image: "/events/workshops/photography.jpg",
    },
    {
      id: 3,
      title: "Digital Marketing Seminar",
      date: "2025-11-05",
      location: "BICC, Dhaka",
      price: 1800,
      desc: "Learn SEO, SEM, and social media marketing.",
      image: "/events/workshops/marketing.jpg",
    },
    {
      id: 4,
      title: "Food Carnival",
      date: "2025-11-12",
      location: "Suhrawardy Udyan, Dhaka",
      price: 500,
      desc: "Street food stalls and cultural food fest.",
      image: "/events/workshops/foodcarnival.jpg",
    },
    {
      id: 5,
      title: "Art & Painting Class",
      date: "2025-11-20",
      location: "Fine Arts Institute, Dhaka",
      price: 800,
      desc: "Hands-on painting and drawing workshop.",
      image: "/events/workshops/art.jpg",
    },
    {
      id: 6,
      title: "Public Speaking Workshop",
      date: "2025-12-01",
      location: "Dhaka University Auditorium",
      price: 1000,
      desc: "Improve confidence and presentation skills.",
      image: "/events/workshops/speaking.jpg",
    },
    {
      id: 7,
      title: "Startup Pitch Bootcamp",
      date: "2025-12-10",
      location: "Startup Incubator, Dhaka",
      price: 2000,
      desc: "Pitching and fundraising workshop for startups.",
      image: "/events/workshops/startup.jpg",
    },
    {
      id: 8,
      title: "Coffee Festival",
      date: "2025-12-18",
      location: "Gulshan Club, Dhaka",
      price: 600,
      desc: "Coffee tasting and barista competition.",
      image: "/events/workshops/coffee.jpg",
    },
  ],
};
